from __future__ import annotations

import json
import logging
import math
import shutil
import subprocess
import tempfile
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from models import ClaimNode

LOGGER = logging.getLogger(__name__)

REPORT_SUBTITLE = "Generated by Dialectic \u00b7 YC Bio\u00d7AI Hackathon 2026"
REPORT_FILENAME = "dialectic_report.docx"
REPORT_MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

_ROOT_DIR = Path(__file__).resolve().parent.parent
_FRONTEND_DIR = _ROOT_DIR / "frontend"
_REPORT_SCRIPT = _FRONTEND_DIR / "scripts" / "generate-report.mjs"
_VALIDATE_SCRIPT = _ROOT_DIR / "scripts" / "office" / "validate.py"

_TIER_ORDER = ("critical", "high", "medium", "low")
_TIER_LABELS = {
    "critical": "Critical",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
}
_TIER_COLORS = {
    "critical": "#ff3050",
    "high": "#ff8c00",
    "medium": "#c8e600",
    "low": "#00e5a0",
}
_TAMARIND_VERDICT_COLORS = {
    "node_a_supported": "#00e5a0",
    "node_b_supported": "#00c8ff",
    "both_plausible": "#8250ff",
    "inconclusive": "#ff8c00",
    "skipped": "#3a4055",
}
_CHART_SPECS = {
    "friction_distribution_bar": {"filename": "friction_distribution_bar.png", "width_inches": 8.0, "height_inches": 4.0},
    "ic50_comparison_bar": {"filename": "ic50_comparison_bar.png", "width_inches": 10.0, "height_inches": 5.0},
    "tamarind_verdicts_pie": {"filename": "tamarind_verdicts_pie.png", "width_inches": 6.0, "height_inches": 6.0},
    "binding_affinity_scatter": {"filename": "binding_affinity_scatter.png", "width_inches": 7.0, "height_inches": 7.0},
    "contradiction_network": {"filename": "contradiction_network.png", "width_inches": 10.0, "height_inches": 8.0},
}


def _clean_text(value: Any, default: str = "") -> str:
    text = str(value or "").strip()
    return text or default


def _display_date() -> str:
    now = datetime.now().astimezone()
    return f"{now.strftime('%B')} {now.day}, {now.year}"


def _truncate_text(value: str | None, limit: int) -> str:
    text = _clean_text(value)
    if len(text) <= limit:
        return text
    return f"{text[: max(0, limit - 1)].rstrip()}\u2026"


def _format_number(value: float | int) -> str:
    rounded = round(float(value), 3)
    if rounded.is_integer():
        return str(int(rounded))
    return f"{rounded:.3f}".rstrip("0").rstrip(".")


def _format_quantitative_value(node: ClaimNode) -> str:
    if node.quantitative_value is None:
        return "Not reported"
    unit = _clean_text(node.quantitative_unit)
    return f"{_format_number(node.quantitative_value)} {unit}".strip()


def _safe_ratio(value_a: float | None, value_b: float | None) -> float | None:
    if value_a is None or value_b is None:
        return None
    try:
        low = min(abs(float(value_a)), abs(float(value_b)))
        high = max(abs(float(value_a)), abs(float(value_b)))
    except (TypeError, ValueError):
        return None
    if high == 0:
        return None
    if low == 0:
        return high
    return high / low


def _ratio_label(ratio: float | None) -> str:
    if ratio is None:
        return "n/a"
    if ratio >= 10:
        return f"{ratio:.0f}x"
    return f"{ratio:.1f}x"


def _risk_bucket(score: float | None) -> str:
    value = float(score or 0.0)
    if value >= 0.85:
        return "critical"
    if value >= 0.60:
        return "high"
    if value >= 0.30:
        return "medium"
    return "low"


def _risk_badge(score: float | None) -> str:
    bucket = _risk_bucket(score)
    return f"{_TIER_LABELS[bucket].upper()} {float(score or 0.0):.2f}"


def _friction_distribution(nodes: list[ClaimNode]) -> dict[str, int]:
    distribution = {tier: 0 for tier in _TIER_ORDER}
    for node in nodes:
        distribution[_risk_bucket(node.friction_score)] += 1
    return distribution


def _node_compound_name(node: ClaimNode) -> str:
    candidates = [
        (node.subject_type, node.subject_name),
        (node.object_type, node.object_name),
        (None, node.subject_name),
        (None, node.object_name),
    ]
    for value_type, value in candidates:
        text = _clean_text(value)
        if not text:
            continue
        if value_type is None or "compound" in _clean_text(value_type).lower():
            return text
    return _clean_text(node.subject_name, "Unknown compound")


def _source_host_label(url: str | None) -> str:
    parsed = urlparse(_clean_text(url))
    host = parsed.netloc.lower().split(":")[0]
    if host.startswith("www."):
        host = host[4:]
    if not host:
        return "Source unavailable"
    mapping = {
        "europepmc.org": "Europe PMC",
        "semanticscholar.org": "Semantic Scholar",
        "youtube.com": "YouTube",
        "youtu.be": "YouTube",
        "doi.org": "DOI",
    }
    return mapping.get(host, host)


def _source_label(node: ClaimNode) -> str:
    if node.source_type == "private_csv":
        return _clean_text(node.file_name, "Private CSV")
    if node.source_type == "pdf_document":
        return _clean_text(node.file_name, "PDF document")
    if node.source_type == "web_url":
        return _source_host_label(node.abstract_url)
    if node.source_type == "youtube_video":
        return "YouTube"
    return _source_host_label(node.abstract_url)


def _journal_label(node: ClaimNode) -> str:
    return _clean_text(getattr(node, "journal", None)) or _source_label(node)


def _contradiction_source(node: ClaimNode) -> str:
    year = node.paper_year if node.paper_year is not None else "n.d."
    return f"{year}, {_journal_label(node)}"


def _pair_key(node: ClaimNode) -> tuple[str, str]:
    names = [
        _clean_text(node.subject_name, "Unknown entity"),
        _clean_text(node.object_name, "Unknown entity"),
    ]
    ordered = sorted(names, key=lambda value: value.lower())
    return ordered[0], ordered[1]


def _pair_stats(nodes: list[ClaimNode]) -> list[dict[str, Any]]:
    pair_map: dict[tuple[str, str], dict[str, Any]] = {}
    for node in nodes:
        if not node.contradicting_node_ids:
            continue
        entity_a, entity_b = _pair_key(node)
        record = pair_map.setdefault(
            (entity_a.lower(), entity_b.lower()),
            {
                "entity_a": entity_a,
                "entity_b": entity_b,
                "contradiction_count": 0,
                "max_friction": 0.0,
            },
        )
        record["contradiction_count"] += max(1, len(node.contradicting_node_ids))
        record["max_friction"] = max(record["max_friction"], float(node.friction_score or 0.0))
    return sorted(
        pair_map.values(),
        key=lambda item: (item["contradiction_count"], item["max_friction"], item["entity_a"], item["entity_b"]),
        reverse=True,
    )


def _friction_interpretation(distribution: dict[str, int], total_nodes: int) -> str:
    if total_nodes <= 0:
        return "No claim nodes were available, so no friction profile could be generated."

    hot_count = distribution["critical"] + distribution["high"]
    hot_pct = (hot_count / total_nodes) * 100
    if distribution["critical"] > 0:
        return (
            f"{hot_count} of {total_nodes} claims ({hot_pct:.1f}%) fall into the high-or-critical band, "
            "which indicates that the session contains a concentrated set of contradictions that should be "
            "validated before downstream target decisions are made."
        )
    if hot_count > 0:
        return (
            f"{hot_count} of {total_nodes} claims ({hot_pct:.1f}%) are high risk while none crossed the critical "
            "threshold, suggesting the map is directionally coherent but still contains assay or context mismatches "
            "that can materially change target confidence."
        )
    return (
        "Most claims remained in the medium-or-low band, which suggests the current session is comparatively "
        "coherent and that the remaining disagreements are more likely to be contextual than fatal."
    )


def _select_killer_line(nodes: list[ClaimNode], node_lookup: dict[str, ClaimNode]) -> str:
    scored_nodes = sorted(nodes, key=lambda node: float(node.friction_score or 0.0), reverse=True)

    def best_private_public(nodes_to_scan: list[ClaimNode]) -> str | None:
        for node in nodes_to_scan:
            if not node.contradicting_node_ids:
                continue
            linked_nodes = [
                node_lookup[other_id]
                for other_id in node.contradicting_node_ids
                if other_id in node_lookup
            ]
            for other in linked_nodes:
                sources = {node.source_type, other.source_type}
                if "private_csv" not in sources or "public_abstract" not in sources:
                    continue
                private_node = node if node.source_type == "private_csv" else other
                public_node = other if private_node is node else node
                ratio = _safe_ratio(private_node.quantitative_value, public_node.quantitative_value)
                if ratio is None:
                    continue
                published_nodes = [item for item in linked_nodes if item.source_type != "private_csv"]
                paper_count = len({item.paper_id or item.node_id for item in published_nodes}) or 1
                compound = _node_compound_name(private_node)
                cell_line = _clean_text(private_node.cell_line or public_node.cell_line, "the matched assay")
                return (
                    f"{paper_count} published papers report {compound} achieves "
                    f"{_format_quantitative_value(public_node)} in {cell_line}. Private assay data shows "
                    f"{_format_quantitative_value(private_node)} - a {_ratio_label(ratio)} discrepancy flagged as "
                    "Target Validation Risk."
                )
        return None

    critical_nodes = [node for node in scored_nodes if float(node.friction_score or 0.0) >= 0.85]
    killer_line = best_private_public(critical_nodes)
    if killer_line:
        return killer_line

    killer_line = best_private_public(scored_nodes)
    if killer_line:
        return killer_line

    for node in critical_nodes:
        contradicters = [
            node_lookup[other_id]
            for other_id in node.contradicting_node_ids
            if other_id in node_lookup
        ]
        quantified = [
            other for other in contradicters
            if other.quantitative_value is not None and node.quantitative_value is not None
        ]
        if not quantified:
            continue
        other = quantified[0]
        ratio = _safe_ratio(node.quantitative_value, other.quantitative_value)
        if ratio is None:
            continue
        cell_line = _clean_text(node.cell_line or other.cell_line, "the matched assay")
        compound = _node_compound_name(node)
        return (
            f"Critical claims place {compound} at {_format_quantitative_value(node)} versus "
            f"{_format_quantitative_value(other)} in {cell_line} - a {_ratio_label(ratio)} spread that keeps the "
            "pair above the Target Validation Risk threshold."
        )

    if critical_nodes:
        top = critical_nodes[0]
        return (
            f"The sharpest critical conflict is {top.subject_name} -> {top.object_name}, where "
            f"{len(top.contradicting_node_ids)} competing claims remain unresolved and warrant direct protocol "
            "harmonization before target commitment."
        )

    return (
        "No critical private-versus-published potency gap was present in this session, so the remaining risk is "
        "driven by contextual contradictions that still require follow-up experimentation."
    )


def _executive_summary(
    session_id: str,
    nodes: list[ClaimNode],
    distribution: dict[str, int],
    top_pairs: list[dict[str, Any]],
    node_lookup: dict[str, ClaimNode],
) -> list[str]:
    total_nodes = len(nodes)
    critical_count = distribution["critical"]
    high_count = distribution["high"]
    sentence_one = (
        f"Dialectic analyzed {total_nodes} claim nodes for session {session_id}, flagging {critical_count} as "
        f"critical and {high_count} additional claims as high risk."
    )
    if top_pairs:
        top_pair = top_pairs[0]
        sentence_two = (
            f"The densest contradiction cluster centers on {top_pair['entity_a']} and {top_pair['entity_b']}, "
            f"accumulating {top_pair['contradiction_count']} contradicted claims with a maximum friction score of "
            f"{top_pair['max_friction']:.2f}."
        )
    else:
        sentence_two = (
            "Contradictions are sparse across entity pairs, so the session is currently dominated by isolated risks "
            "rather than one repeated failure mode."
        )
    sentence_three = _select_killer_line(nodes, node_lookup)
    return [sentence_one, sentence_two, sentence_three]


def _unique_tamarind_records(nodes: list[ClaimNode]) -> list[dict[str, Any]]:
    records: dict[str, dict[str, Any]] = {}
    for node in nodes:
        verdict = node.tamarind_verdict if isinstance(node.tamarind_verdict, dict) else None
        if not verdict:
            continue
        key = _clean_text(verdict.get("tamarind_job_id"))
        if not key:
            key = "::".join(
                [
                    _clean_text(verdict.get("compound_a")),
                    _clean_text(verdict.get("compound_b")),
                    _clean_text(verdict.get("verdict")),
                    _clean_text(verdict.get("binding_affinity_a")),
                    _clean_text(verdict.get("binding_affinity_b")),
                ]
            )
        existing = records.get(key)
        record = {
            "key": key,
            "node": node,
            "verdict": verdict,
            "friction_score": float(node.friction_score or 0.0),
            "compound_a": _clean_text(verdict.get("compound_a"), _node_compound_name(node)),
            "compound_b": _clean_text(verdict.get("compound_b"), _clean_text(node.object_name, "Comparison claim")),
            "binding_affinity_a": verdict.get("binding_affinity_a"),
            "binding_affinity_b": verdict.get("binding_affinity_b"),
            "mock": bool(verdict.get("mock")),
        }
        if existing is None or record["friction_score"] > existing["friction_score"]:
            records[key] = record
    return list(records.values())


def compute_session_readiness(session_status: str, nodes: list[ClaimNode], progress: int = 0) -> dict[str, Any]:
    tamarind_jobs_total = sum(1 for node in nodes if float(node.friction_score or 0.0) >= 0.85)
    tamarind_jobs_done = 0
    tamarind_jobs_failed = 0
    for node in nodes:
        if float(node.friction_score or 0.0) < 0.85:
            continue
        verdict = node.tamarind_verdict if isinstance(node.tamarind_verdict, dict) else None
        if verdict is None:
            continue
        verdict_name = _clean_text(verdict.get("verdict")).lower()
        if verdict_name and verdict_name != "skipped":
            tamarind_jobs_done += 1
        else:
            tamarind_jobs_failed += 1

    debate_complete = session_status == "complete"
    nodes_with_quantitative = sum(1 for node in nodes if node.quantitative_value is not None)
    tamarind_ratio = (
        (tamarind_jobs_done + tamarind_jobs_failed) / tamarind_jobs_total
        if tamarind_jobs_total
        else 0.0
    )
    debate_ratio = 1.0 if debate_complete else max(0.0, min(float(progress or 0) / 100.0, 1.0))
    ready = (
        debate_complete
        and tamarind_jobs_total > 0
        and (tamarind_jobs_done + tamarind_jobs_failed) == tamarind_jobs_total
    )

    if ready:
        percent_complete = 100.0
    elif debate_complete:
        percent_complete = round(65.0 + (35.0 * tamarind_ratio), 1)
    else:
        percent_complete = round(65.0 * debate_ratio, 1)

    return {
        "ready": ready,
        "checks": {
            "debate_complete": debate_complete,
            "tamarind_jobs_total": tamarind_jobs_total,
            "tamarind_jobs_done": tamarind_jobs_done,
            "tamarind_jobs_failed": tamarind_jobs_failed,
            "nodes_total": len(nodes),
            "nodes_with_quantitative": nodes_with_quantitative,
        },
        "percent_complete": percent_complete,
    }


def _contradiction_sections(nodes: list[ClaimNode], node_lookup: dict[str, ClaimNode]) -> list[dict[str, Any]]:
    hot_nodes = [
        node for node in nodes
        if float(node.friction_score or 0.0) >= 0.60
    ]
    hot_nodes.sort(
        key=lambda node: (
            float(node.friction_score or 0.0),
            len(node.contradicting_node_ids),
            _clean_text(node.subject_name),
        ),
        reverse=True,
    )

    sections: list[dict[str, Any]] = []
    for node in hot_nodes:
        contradicters = [
            node_lookup[other_id]
            for other_id in node.contradicting_node_ids
            if other_id in node_lookup
        ]
        contradicters.sort(
            key=lambda other: (
                float(other.friction_score or 0.0),
                other.paper_year or 0,
                _clean_text(other.subject_name),
            ),
            reverse=True,
        )
        published_count = sum(1 for other in contradicters if other.source_type != "private_csv")
        contradiction_heading = (
            f"Contradicts {published_count} published claims"
            if published_count > 0
            else f"Contradicts {len(contradicters)} claims"
        )
        tamarind_verdict = node.tamarind_verdict if isinstance(node.tamarind_verdict, dict) else None
        sections.append(
            {
                "heading": f"{_clean_text(node.subject_name, 'Unknown subject')} \u2192 {_clean_text(node.object_name, 'Unknown object')}",
                "risk_badge": _risk_badge(node.friction_score),
                "risk_color": _TIER_COLORS[_risk_bucket(node.friction_score)],
                "claim_text": _clean_text(node.claim_text, "Claim text unavailable."),
                "polarity": _clean_text(node.polarity, "unknown"),
                "cell_line": _clean_text(node.cell_line, "Not reported"),
                "quantitative_value": _format_quantitative_value(node),
                "skeptic_rationale": _clean_text(node.skeptic_rationale),
                "contradiction_summary": contradiction_heading if contradicters else "",
                "contradictions": [
                    {
                        "claim_text": _clean_text(other.claim_text, "Claim text unavailable."),
                        "source": _contradiction_source(other),
                    }
                    for other in contradicters
                ],
                "tamarind_verdict": tamarind_verdict,
            }
        )
    return sections


def _semantic_map_summary(nodes: list[ClaimNode]) -> tuple[list[dict[str, Any]], str]:
    top_pairs = _pair_stats(nodes)[:10]
    explanation = (
        "Semantic proximity is computed from text-embedding-3-small vectors built from claim text, subject, object, "
        "and assay context. Each vector is polarity-shifted before normalization so promotes and inhibits claims "
        "separate even when they mention the same entities, allowing contradiction density to be summarized as an "
        "entity-pair map rather than a simple keyword count."
    )
    return top_pairs, explanation


def _methodology_sections() -> list[dict[str, Any]]:
    return [
        {
            "heading": "Claim Extraction",
            "paragraphs": [
                "Every source is normalized into a ClaimNode schema containing a subject, predicate, and object, plus quantitative, contextual, and provenance metadata. Private CSV, PDF, URL, YouTube, and literature sources therefore land in a common triple format before contradiction analysis begins.",
            ],
        },
        {
            "heading": "Contradiction Detection",
            "paragraphs": [
                "Dialectic runs a two-pass debate pipeline. Rule 1 performs coarse semantic clustering on a 4x4 UMAP grid and assigns a low baseline friction from the local skeptic summary. Rule 2 evaluates candidate cross-corpus contradiction pairs with heuristic and model-based confirmation. Rule 3 escalates confirmed critical pairs to structural arbitration when friction reaches 0.85 or higher.",
            ],
        },
        {
            "heading": "Friction Scoring",
            "paragraphs": [
                "Node friction is the maximum of baseline cluster tension and confirmed contradiction contributions. The operational thresholds in code are HIGH at 0.60 and CRITICAL at 0.85. Heuristic anchors are 0.85 for polarity reversals, 0.80 for >100x magnitude gaps, 0.60 for 10-100x magnitude gaps, and 0.70 for strong private-versus-published conflicts, with context penalties applied for mismatched cell lines or units.",
            ],
        },
        {
            "heading": "Structural Arbitration",
            "paragraphs": [
                "Critical contradiction pairs are sent to Tamarind Bio DiffDock against KRAS G12C structure PDB 6OIM. The docking layer compares structural support for the disputed claims and records verdict text, binding scores, and confidence.",
                "SMILES tracked in code: sotorasib / AMG-510 = CC1=CC(=C(C=C1)NC(=O)C2=CN=C(N=C2)NC3=CC(=C(C=C3)N4CC(C4)N(C)C(=O)/C=C/CN(C)C)F)F. Adagrasib / MRTX849 = C[C@@H]1CC[C@@H](C(=O)N2CC(=C)C[C@@H]2C3=C(C=CC(=N3)C4=NC5=CC=CC=C5N4C)Cl)O1. ARS-1620 = CC1=CC(=C(C(=C1)Cl)NC2=NC=C(C(=N2)NCC3=CC=C(C=C3)F)Cl)Cl.",
            ],
        },
        {
            "heading": "Embedding",
            "paragraphs": [
                "Embeddings are generated with text-embedding-3-small over a concatenation of polarity, claim text, subject, object, and assay context. The polarity shift is implemented exactly as vec = embedding + POLARITY_DELTA followed by vec = vec / ||vec||, where DELTA is +0.15 for promotes, -0.15 for inhibits, and 0.0 for neutral or ambiguous claims.",
            ],
        },
        {
            "heading": "Dimensionality Reduction",
            "paragraphs": [
                "The semantic map uses UMAP with cosine distance, n_components = 2, random_state = 42, min_dist = 0.25, and n_neighbors = min(15, len(nodes) - 1). Those projected coordinates feed the map layout and the coarse clustering pass used during contradiction analysis.",
            ],
        },
    ]


def _citation_entries(nodes: list[ClaimNode]) -> tuple[list[dict[str, Any]], bool]:
    citation_map: dict[str, dict[str, Any]] = {}
    mock_verdict_present = any(
        isinstance(node.tamarind_verdict, dict) and bool(node.tamarind_verdict.get("mock"))
        for node in nodes
    )
    for node in nodes:
        if not node.abstract_url:
            continue
        key = _clean_text(node.paper_id or node.abstract_url)
        if not key:
            continue
        current = citation_map.get(key)
        candidate = {
            "authors": _clean_text(node.paper_authors, "Unknown authors"),
            "year": node.paper_year,
            "claim_text": _truncate_text(_clean_text(node.claim_text), 80),
            "journal": _journal_label(node),
            "url": _clean_text(node.abstract_url),
            "citation_count": int(node.citation_count or 0),
        }
        if current is None or (
            (candidate["year"] or 0, candidate["citation_count"]) > (current["year"] or 0, current["citation_count"])
        ):
            citation_map[key] = candidate

    ordered = sorted(
        citation_map.values(),
        key=lambda item: (item["year"] is not None, item["year"] or 0, item["citation_count"]),
        reverse=True,
    )
    return ordered, mock_verdict_present


def _is_ic50_node(node: ClaimNode) -> bool:
    unit = _clean_text(node.quantitative_unit).lower()
    return node.quantitative_value is not None and ("nm" in unit or "ic50" in unit)


def _build_ic50_discrepancies(nodes: list[ClaimNode]) -> list[dict[str, Any]]:
    grouped: dict[str, dict[str, Any]] = {}
    for node in nodes:
        if not _is_ic50_node(node):
            continue
        compound = _node_compound_name(node)
        record = grouped.setdefault(
            compound.lower(),
            {
                "compound": compound,
                "private_values": [],
                "public_values": [],
            },
        )
        if node.source_type == "private_csv":
            record["private_values"].append(node)
        else:
            record["public_values"].append(node)

    rows: list[dict[str, Any]] = []
    for entry in grouped.values():
        if not entry["private_values"]:
            continue
        private_node = max(entry["private_values"], key=lambda node: float(node.quantitative_value or 0.0))
        public_node = (
            min(entry["public_values"], key=lambda node: float(node.quantitative_value or 0.0))
            if entry["public_values"]
            else None
        )
        fold = _safe_ratio(
            private_node.quantitative_value,
            public_node.quantitative_value if public_node else None,
        )
        high_risk = bool(fold is not None and fold > 10)
        rows.append(
            {
                "compound": entry["compound"],
                "private_ic50": _format_quantitative_value(private_node),
                "published_ic50": _format_quantitative_value(public_node) if public_node else "No matched literature",
                "fold_difference": _ratio_label(fold),
                "risk": "CRITICAL" if high_risk else "Monitor",
                "risk_color": "#ff3050" if high_risk else "#1f2430",
                "risk_bold": high_risk,
            }
        )
    rows.sort(key=lambda item: (item["risk"] == "CRITICAL", item["fold_difference"], item["compound"]), reverse=True)
    return rows


def _build_structural_sections(nodes: list[ClaimNode]) -> list[dict[str, Any]]:
    records = [
        record for record in _unique_tamarind_records(nodes)
        if record["friction_score"] >= 0.85
    ]
    records.sort(key=lambda item: item["friction_score"], reverse=True)

    sections: list[dict[str, Any]] = []
    for record in records:
        verdict = record["verdict"]
        verdict_name = _clean_text(verdict.get("verdict"), "inconclusive")
        affinity_a = verdict.get("binding_affinity_a")
        affinity_b = verdict.get("binding_affinity_b")
        stronger = "Equal affinity"
        if affinity_a is not None and affinity_b is not None:
            if affinity_a > affinity_b:
                stronger = "Node A stronger"
            elif affinity_b > affinity_a:
                stronger = "Node B stronger"

        sections.append(
            {
                "heading": f"{record['compound_a']} vs {record['compound_b']}",
                "verdict": verdict_name,
                "verdict_display": verdict_name.replace("_", " ").upper(),
                "verdict_color": _TAMARIND_VERDICT_COLORS.get(verdict_name, "#ff8c00"),
                "structural_rationale": _clean_text(verdict.get("structural_rationale"), "No structural rationale reported."),
                "binding_rows": [
                    {
                        "label": "Node A claim",
                        "affinity": _format_number(affinity_a) if affinity_a is not None else "Not reported",
                        "interpretation": (
                            "stronger" if affinity_a is not None and affinity_b is not None and affinity_a > affinity_b
                            else "weaker" if affinity_a is not None and affinity_b is not None and affinity_a < affinity_b
                            else stronger.lower()
                        ),
                    },
                    {
                        "label": "Node B claim",
                        "affinity": _format_number(affinity_b) if affinity_b is not None else "Not reported",
                        "interpretation": (
                            "stronger" if affinity_a is not None and affinity_b is not None and affinity_b > affinity_a
                            else "weaker" if affinity_a is not None and affinity_b is not None and affinity_b < affinity_a
                            else stronger.lower()
                        ),
                    },
                ],
                "confidence": f"{round(float(verdict.get('confidence') or 0.0) * 100):.0f}%",
                "job_note": (
                    "Docking performed via Tamarind Bio DiffDock API. "
                    f"Protein: KRAS G12C (PDB: 6OIM). Job ID: {_clean_text(verdict.get('tamarind_job_id'), 'n/a')}"
                ),
                "mock": bool(verdict.get("mock")),
            }
        )
    return sections


def _import_chart_modules():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import networkx as nx
    from matplotlib.colors import LinearSegmentedColormap

    return plt, nx, LinearSegmentedColormap


def _apply_dark_theme(ax, title: str) -> None:
    ax.set_facecolor("#0c0e12")
    ax.figure.patch.set_facecolor("#0c0e12")
    ax.set_title(title, color="white", fontsize=13, pad=14)
    ax.tick_params(colors="white")
    for spine in ax.spines.values():
        spine.set_color("#1e2430")
    ax.grid(color="#1e2430", alpha=0.65)
    ax.set_axisbelow(True)


def _render_empty_chart(ax, title: str, message: str) -> None:
    _apply_dark_theme(ax, title)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.text(0.5, 0.5, message, color="white", fontsize=11, ha="center", va="center", transform=ax.transAxes)


def _save_figure(fig, path: Path) -> None:
    fig.tight_layout()
    fig.savefig(path, dpi=150, facecolor=fig.get_facecolor(), bbox_inches="tight")
    fig.clf()


def _generate_friction_distribution_chart(path: Path, nodes: list[ClaimNode]) -> None:
    plt, _, _ = _import_chart_modules()
    distribution = _friction_distribution(nodes)
    labels = ["Critical", "High", "Medium", "Low"]
    values = [distribution["critical"], distribution["high"], distribution["medium"], distribution["low"]]
    colors = ["#ff3050", "#ff8c00", "#c8e600", "#00e5a0"]
    fig, ax = plt.subplots(figsize=(8, 4))
    _apply_dark_theme(ax, "Friction Score Distribution")
    ax.barh(labels, values, color=colors)
    ax.set_xlabel("Node count", color="white")
    ax.set_ylabel("Risk tier", color="white")
    ax.invert_yaxis()
    _save_figure(fig, path)
    plt.close(fig)


def _generate_ic50_comparison_chart(path: Path, nodes: list[ClaimNode]) -> None:
    plt, _, _ = _import_chart_modules()
    ic50_nodes = [node for node in nodes if _is_ic50_node(node)]
    grouped: dict[str, list[ClaimNode]] = defaultdict(list)
    for node in ic50_nodes:
        grouped[_node_compound_name(node)].append(node)

    fig, ax = plt.subplots(figsize=(10, 5))
    if not grouped:
        _render_empty_chart(ax, "IC50 Comparison: Private Assay vs Published Literature", "No IC50 measurements available.")
        _save_figure(fig, path)
        plt.close(fig)
        return

    _apply_dark_theme(ax, "IC50 Comparison: Private Assay vs Published Literature")
    compounds = sorted(grouped.keys())
    group_gap = 1.2
    x_positions: list[float] = []
    x_labels: list[str] = []
    x_meta: dict[str, list[tuple[float, ClaimNode]]] = {}
    cursor = 0.0
    for compound in compounds:
        members = sorted(
            grouped[compound],
            key=lambda node: (node.source_type != "private_csv", float(node.quantitative_value or 0.0)),
        )
        x_meta[compound] = []
        for index, node in enumerate(members):
            xpos = cursor + index
            x_positions.append(xpos)
            x_labels.append(compound if index == 0 else "")
            x_meta[compound].append((xpos, node))
        cursor += max(1, len(members)) + group_gap

    for compound in compounds:
        for xpos, node in x_meta[compound]:
            color = "#ff8c00" if node.source_type == "private_csv" else "#00c8ff"
            ax.bar(xpos, float(node.quantitative_value or 0.0), color=color, width=0.7)

        private_values = [node for _, node in x_meta[compound] if node.source_type == "private_csv"]
        public_values = [node for _, node in x_meta[compound] if node.source_type != "private_csv"]
        if private_values and public_values:
            private_peak = max(float(node.quantitative_value or 0.0) for node in private_values)
            public_floor = min(float(node.quantitative_value or 0.0) for node in public_values)
            if public_floor > 0 and private_peak > public_floor * 10:
                left = x_meta[compound][0][0] - 0.2
                right = x_meta[compound][-1][0] + 0.2
                y_top = private_peak * 1.25
                y_mid = public_floor * 1.05
                ax.plot([left, left, right, right], [y_mid, y_top, y_top, y_mid], color="#ff3050", linewidth=1.2)
                ax.text(
                    (left + right) / 2,
                    y_top * 1.06,
                    f"{round(private_peak / public_floor):.0f}x discrepancy",
                    color="#ff3050",
                    fontsize=8,
                    ha="center",
                )

    ax.set_yscale("log")
    ax.axhline(10, color="#ff3050", linestyle="--", linewidth=1)
    ax.text(0.01, 10, "1 nM threshold", color="#ff3050", fontsize=8, va="bottom", transform=ax.get_yaxis_transform())
    ax.set_ylabel("IC50 (nM, log scale)", color="white")
    ax.set_xticks(x_positions)
    ax.set_xticklabels(x_labels, rotation=35, ha="right", color="white", fontsize=8)
    ax.legend(
        handles=[
            plt.Rectangle((0, 0), 1, 1, color="#ff8c00", label="private_csv"),
            plt.Rectangle((0, 0), 1, 1, color="#00c8ff", label="public_abstract"),
        ],
        facecolor="#0c0e12",
        edgecolor="#1e2430",
        labelcolor="white",
        fontsize=8,
    )
    _save_figure(fig, path)
    plt.close(fig)


def _generate_tamarind_pie_chart(path: Path, nodes: list[ClaimNode]) -> None:
    plt, _, _ = _import_chart_modules()
    verdict_order = ["node_a_supported", "node_b_supported", "both_plausible", "inconclusive", "skipped"]
    counts = Counter(
        _clean_text(record["verdict"].get("verdict"), "skipped")
        for record in _unique_tamarind_records(nodes)
    )
    fig, ax = plt.subplots(figsize=(6, 6))
    if not counts:
        _render_empty_chart(ax, "Structural Arbitration Outcomes (Tamarind DiffDock)", "No Tamarind verdicts available.")
        _save_figure(fig, path)
        plt.close(fig)
        return

    ax.set_facecolor("#0c0e12")
    fig.patch.set_facecolor("#0c0e12")
    labels = []
    sizes = []
    colors = []
    total = sum(counts.values()) or 1
    for verdict in verdict_order:
        count = counts.get(verdict, 0)
        if count <= 0:
            continue
        labels.append(f"{verdict}\n{count} ({(count / total) * 100:.0f}%)")
        sizes.append(count)
        colors.append(_TAMARIND_VERDICT_COLORS[verdict])

    ax.pie(
        sizes,
        labels=labels,
        colors=colors,
        textprops={"color": "white", "fontsize": 8},
        startangle=90,
        wedgeprops={"linewidth": 1, "edgecolor": "#0c0e12"},
    )
    ax.set_title("Structural Arbitration Outcomes (Tamarind DiffDock)", color="white", fontsize=13, pad=14)
    _save_figure(fig, path)
    plt.close(fig)


def _generate_binding_affinity_scatter(path: Path, nodes: list[ClaimNode]) -> None:
    plt, _, LinearSegmentedColormap = _import_chart_modules()
    records = [
        record for record in _unique_tamarind_records(nodes)
        if record["binding_affinity_a"] is not None and record["binding_affinity_b"] is not None
    ]
    fig, ax = plt.subplots(figsize=(7, 7))
    if not records:
        _render_empty_chart(ax, "Binding Affinity: Contradicting Node Pairs", "No paired binding affinities available.")
        _save_figure(fig, path)
        plt.close(fig)
        return

    _apply_dark_theme(ax, "Binding Affinity: Contradicting Node Pairs")
    cmap = LinearSegmentedColormap.from_list("friction_scale", ["#00e5a0", "#ff3050"])
    xs = [float(record["binding_affinity_a"]) for record in records]
    ys = [float(record["binding_affinity_b"]) for record in records]
    scores = [float(record["friction_score"]) for record in records]
    scatter = ax.scatter(xs, ys, c=scores, cmap=cmap, s=80, edgecolors="#0c0e12", linewidths=0.8)
    lower = min(xs + ys)
    upper = max(xs + ys)
    ax.plot([lower, upper], [lower, upper], linestyle="--", color="#ffffff", linewidth=1)
    ax.text(0.03, 0.96, "Equal affinity", color="white", fontsize=8, transform=ax.transAxes, va="top")
    for record, x_value, y_value in zip(records, xs, ys):
        ax.annotate(record["compound_a"], (x_value, y_value), color="white", fontsize=8, xytext=(4, 4), textcoords="offset points")
    ax.set_xlabel("Binding affinity A", color="white")
    ax.set_ylabel("Binding affinity B", color="white")
    colorbar = fig.colorbar(scatter, ax=ax)
    colorbar.set_label("Friction Score", color="white")
    colorbar.ax.yaxis.set_tick_params(color="white")
    for tick in colorbar.ax.get_yticklabels():
        tick.set_color("white")
    _save_figure(fig, path)
    plt.close(fig)


def _generate_contradiction_network(path: Path, nodes: list[ClaimNode]) -> None:
    plt, nx, _ = _import_chart_modules()
    graph = nx.Graph()
    node_citations: dict[str, int] = defaultdict(int)
    node_risk: dict[str, str] = defaultdict(lambda: "low")
    edge_weights: dict[tuple[str, str], float] = {}

    for node in nodes:
        if not node.contradicting_node_ids:
            continue
        subject = _clean_text(node.subject_name, "Unknown subject")
        obj = _clean_text(node.object_name, "Unknown object")
        for name in (subject, obj):
            node_citations[name] = max(node_citations[name], int(node.citation_count or 0))
            current_risk = node_risk[name]
            incoming_risk = _risk_bucket(node.friction_score)
            if _TIER_ORDER.index(incoming_risk) < _TIER_ORDER.index(current_risk):
                node_risk[name] = incoming_risk
        edge_key = tuple(sorted((subject, obj)))
        edge_weights[edge_key] = max(edge_weights.get(edge_key, 0.0), float(node.friction_score or 0.0))

    fig, ax = plt.subplots(figsize=(10, 8))
    if not edge_weights:
        _render_empty_chart(ax, "Contradiction Network - Entity Relationships", "No contradiction edges available.")
        _save_figure(fig, path)
        plt.close(fig)
        return

    _apply_dark_theme(ax, "Contradiction Network - Entity Relationships")
    for (entity_a, entity_b), weight in edge_weights.items():
        graph.add_edge(entity_a, entity_b, weight=weight * 3)

    positions = nx.spring_layout(graph, seed=42, k=2.0)
    raw_sizes = [node_citations.get(name, 0) for name in graph.nodes]
    max_size = max(raw_sizes) if raw_sizes else 1
    min_size = min(raw_sizes) if raw_sizes else 0

    def scaled_size(value: int) -> float:
        if max_size == min_size:
            return 300
        return 100 + (((value - min_size) / (max_size - min_size)) * 700)

    node_sizes = [scaled_size(node_citations.get(name, 0)) for name in graph.nodes]
    node_colors = []
    for name in graph.nodes:
        risk = node_risk.get(name, "low")
        if risk == "critical":
            node_colors.append("#ff3050")
        elif risk == "high":
            node_colors.append("#ff8c00")
        else:
            node_colors.append("#00e5a0")

    nx.draw_networkx_edges(
        graph,
        positions,
        ax=ax,
        width=[graph[edge_a][edge_b]["weight"] for edge_a, edge_b in graph.edges],
        edge_color="#6b7590",
        alpha=0.65,
    )
    nx.draw_networkx_nodes(
        graph,
        positions,
        ax=ax,
        node_size=node_sizes,
        node_color=node_colors,
        edgecolors="#0c0e12",
        linewidths=1.2,
    )
    nx.draw_networkx_labels(graph, positions, ax=ax, font_size=8, font_color="white")
    ax.set_xticks([])
    ax.set_yticks([])
    _save_figure(fig, path)
    plt.close(fig)


def _build_chart_manifest(chart_dir: Path, nodes: list[ClaimNode], warnings: list[str]) -> dict[str, dict[str, Any]]:
    chart_paths: dict[str, dict[str, Any]] = {}
    generators = {
        "friction_distribution_bar": _generate_friction_distribution_chart,
        "ic50_comparison_bar": _generate_ic50_comparison_chart,
        "tamarind_verdicts_pie": _generate_tamarind_pie_chart,
        "binding_affinity_scatter": _generate_binding_affinity_scatter,
        "contradiction_network": _generate_contradiction_network,
    }
    for chart_key, generator in generators.items():
        spec = _CHART_SPECS[chart_key]
        path = chart_dir / spec["filename"]
        try:
            generator(path, nodes)
            chart_paths[chart_key] = {
                "path": str(path),
                "width_inches": spec["width_inches"],
                "height_inches": spec["height_inches"],
            }
        except Exception as exc:
            LOGGER.warning("Chart generation failed for %s: %s", chart_key, exc)
            warnings.append(f"{chart_key}: {exc}")
    return chart_paths


def _prepare_chart_dir(session_id: str) -> Path:
    chart_dir = Path(tempfile.gettempdir()) / f"dialectic_charts_{session_id}"
    if chart_dir.exists():
        shutil.rmtree(chart_dir, ignore_errors=True)
    chart_dir.mkdir(parents=True, exist_ok=True)
    return chart_dir


def cleanup_report_artifacts(payload: dict[str, Any]) -> None:
    chart_dir = _clean_text(payload.get("chart_artifacts_dir"))
    if chart_dir:
        shutil.rmtree(chart_dir, ignore_errors=True)


def build_report_payload(
    session_id: str,
    nodes: list[ClaimNode],
    report_title: str | None = None,
    session_status: str = "complete",
    session_progress: int = 100,
) -> dict[str, Any]:
    node_lookup = {node.node_id: node for node in nodes}
    distribution = _friction_distribution(nodes)
    contradiction_pairs, semantic_map_text = _semantic_map_summary(nodes)
    readiness = compute_session_readiness(session_status, nodes, session_progress)
    chart_warnings: list[str] = []
    chart_dir = _prepare_chart_dir(session_id)
    charts = _build_chart_manifest(chart_dir, nodes, chart_warnings)
    citations, mock_verdict_present = _citation_entries(nodes)
    unique_tamarind_records = _unique_tamarind_records(nodes)
    payload = {
        "report_title": _clean_text(report_title, "Target Validation Risk Report"),
        "subtitle": REPORT_SUBTITLE,
        "date": _display_date(),
        "session_id": session_id,
        "node_count": len(nodes),
        "readiness": readiness,
        "cover_status": "Experiment Status: ALL TAMARIND JOBS COMPLETE",
        "cover_counts": (
            f"{len(unique_tamarind_records)} docking simulations \u00b7 "
            f"{readiness['checks']['tamarind_jobs_done'] + readiness['checks']['tamarind_jobs_failed']} contradictions resolved"
        ),
        "executive_summary": _executive_summary(session_id, nodes, distribution, contradiction_pairs, node_lookup),
        "experiment_results": {
            "ic50_analysis": {
                "discrepancy_rows": _build_ic50_discrepancies(nodes),
            },
            "structural_docking": {
                "sections": _build_structural_sections(nodes),
            },
        },
        "friction_distribution": [
            {
                "risk_level": _TIER_LABELS[tier],
                "node_count": distribution[tier],
                "percentage": f"{(distribution[tier] / len(nodes) * 100):.1f}%" if nodes else "0.0%",
                "color_code": _TIER_COLORS[tier],
            }
            for tier in _TIER_ORDER
        ],
        "friction_interpretation": _friction_interpretation(distribution, len(nodes)),
        "contradiction_analysis": _contradiction_sections(nodes, node_lookup),
        "semantic_map_pairs": contradiction_pairs[:10],
        "semantic_map_methodology": semantic_map_text,
        "methodology_sections": _methodology_sections(),
        "citations": citations,
        "citation_footer": [
            "Structural docking data provided by Tamarind Bio (app.tamarind.bio). Protein structure: KRAS G12C, PDB ID: 6OIM, retrieved from RCSB Protein Data Bank.",
            "* Structural verdicts marked DEMO MODE were generated with simulated docking parameters for demonstration purposes."
            if mock_verdict_present
            else "",
        ],
        "charts": charts,
        "chart_artifacts_dir": str(chart_dir),
        "chart_warnings": chart_warnings,
    }
    return payload


def _run_validation(document_bytes: bytes) -> bool:
    if not _VALIDATE_SCRIPT.exists():
        return False

    with tempfile.TemporaryDirectory(prefix="dialectic-docx-") as temp_dir:
        report_path = Path(temp_dir) / "report.docx"
        report_path.write_bytes(document_bytes)
        process = subprocess.run(
            ["python3", str(_VALIDATE_SCRIPT), str(report_path)],
            cwd=str(_ROOT_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        return process.returncode == 0


def render_report_docx(payload: dict[str, Any]) -> tuple[bytes, bool]:
    if not _REPORT_SCRIPT.exists():
        raise FileNotFoundError(f"Report generator script was not found at {_REPORT_SCRIPT}.")

    process = subprocess.run(
        ["node", str(_REPORT_SCRIPT)],
        cwd=str(_FRONTEND_DIR),
        input=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if process.returncode != 0:
        error_text = process.stderr.decode("utf-8", errors="replace").strip() or "Unknown docx generation error."
        raise RuntimeError(error_text)
    if not process.stdout:
        raise RuntimeError("Report generation completed without producing a document.")

    validation_ok = _run_validation(process.stdout)
    return process.stdout, validation_ok
